name: poc_petkeepper_lite
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.3
  google_sign_in: ^7.2.0
  flutter_riverpod: ^3.0.3
  image_picker: ^1.2.0
  cloud_functions: ^6.0.3
  flutter_facebook_auth: ^7.1.2
  uuid: ^4.5.1
  riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
 
  uses-material-design: true
