// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6BIppo65DLwGfPwhVCSqmsat6vBY1TTw',
    appId: '1:819939293233:web:50b12b0b60ccc8238abd10',
    messagingSenderId: '819939293233',
    projectId: 'petkeeper-lite-ce969',
    authDomain: 'petkeeper-lite-ce969.firebaseapp.com',
    databaseURL: 'https://petkeeper-lite-ce969-default-rtdb.firebaseio.com',
    storageBucket: 'petkeeper-lite-ce969.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbOB4KEyoy-gzX2Dky3lP_5j_ONVetFMM',
    appId: '1:819939293233:android:564303c425ee527d8abd10',
    messagingSenderId: '819939293233',
    projectId: 'petkeeper-lite-ce969',
    databaseURL: 'https://petkeeper-lite-ce969-default-rtdb.firebaseio.com',
    storageBucket: 'petkeeper-lite-ce969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8uqWXPKO_9Y3xroDpvHIE2ASMOW2Sh1U',
    appId: '1:819939293233:ios:cf0dec3349b515538abd10',
    messagingSenderId: '819939293233',
    projectId: 'petkeeper-lite-ce969',
    databaseURL: 'https://petkeeper-lite-ce969-default-rtdb.firebaseio.com',
    storageBucket: 'petkeeper-lite-ce969.firebasestorage.app',
    iosBundleId: 'com.example.pocPetkeepperLite',
  );
}
